RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
VIA_ENABLE = yes
RGB_MATRIX_CUSTOM_KB = yes
RGB_MATRIX_CONTROL_ENABLE = yes
UNDERGLOW_RGB_MATRIX_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_TRIGGER_ENABLE = yes
WPM_ENABLE = yes
ALT_TAB_MARCO_ENABLE = yes
RADIAL_CONTROLLER_ENABLE = yes
VIA_CUSTOM_KEYCODE_ENABLE = yes

ifeq ($(PLATFORM), AVR)
  LTO_ENABLE = yes
endif


ifneq ($(findstring GD32VF103, $(MCU)),)
  OPENRGB_ENABLE = no
else
  OPENRGB_ENABLE = yes
endif

