#ifdef RGB_MATRIX_CUSTOM_EFFECT_ANIMATION
#define RGB_MATRIX_EFFECT_CANDY_TAP
#define RGB_MATRIX_EFFECT_CYCLE_BAND_PINWHEEL_SAT
#define RGB_MATRIX_EFFECT_CYCLE_BAND_PINWHEEL_VAL
#define RGB_MATRIX_EFFECT_CYCLE_BAND_SPIRAL_SAT
#define RGB_MATRIX_EFFECT_CYCLE_BAND_SPIRAL_VAL
#define RGB_MATRIX_EFFECT_CYCLE_BANDVAL
#define RGB_MATRIX_EFFECT_CYCLE_BREATHING
#define RGB_MATRIX_EFFECT_CYCLE_DOWN_UP
#define RGB_MATRIX_EFFECT_CYCLE_IN_OUT_DUAL
#define RGB_MATRIX_EFFECT_CYCLE_IN_OUT
#define RGB_MATRIX_EFFECT_CYCLE_MULTISPLASH
#define RGB_MATRIX_EFFECT_CYCLE_REACTIVE_MULTICROSS
#define RGB_MATRIX_EFFECT_CYCLE_REACTIVE_MULTINEXUS
#define RGB_MATRIX_EFFECT_CYCLE_REACTIVE_MULTIWIDE
#define RGB_MATRIX_EFFECT_CYCLE_RIGHT_LEFT
#define RGB_MATRIX_EFFECT_FRACTAL_RGB
#define RGB_MATRIX_EFFECT_FRACTAL
#define RGB_MATRIX_EFFECT_KITT_RGB
#define RGB_MATRIX_EFFECT_REACTIVE_MULTICROSS_RGB
#define RGB_MATRIX_EFFECT_REACTIVE_MULTINEXUS_RGB
#define RGB_MATRIX_EFFECT_REACTIVE_MULTIWIDE_RGB
#define RGB_MATRIX_EFFECT_CYCLE_SIN_WAVE
#define RGB_MATRIX_EFFECT_RAINBOW_SIN_WAVE
#define RGB_MATRIX_EFFECT_RAINBOW_SIN_WAVE_REVERSE
#endif

#include "zqlib/rgb_matrix_effect/cycle_breathing.h"
#include "zqlib/rgb_matrix_effect/cycle_bandval.h"
#include "zqlib/rgb_matrix_effect/cycle_band_pinwheel_sat.h"
#include "zqlib/rgb_matrix_effect/cycle_band_pinwheel_val.h"
#include "zqlib/rgb_matrix_effect/cycle_band_spiral_sat.h"
#include "zqlib/rgb_matrix_effect/cycle_band_spiral_val.h"
#include "zqlib/rgb_matrix_effect/cycle_right_left.h"
#include "zqlib/rgb_matrix_effect/cycle_down_up.h"
#include "zqlib/rgb_matrix_effect/cycle_in_out.h"
#include "zqlib/rgb_matrix_effect/cycle_in_out_dual.h"
#include "zqlib/rgb_matrix_effect/fractal.h"
#include "zqlib/rgb_matrix_effect/fractal_rgb.h"
#include "zqlib/rgb_matrix_effect/kitt_rgb.h"
#include "zqlib/rgb_matrix_effect/cycle_sin_wave.h"
#include "zqlib/rgb_matrix_effect/rainbow_sin_wave.h"
#include "zqlib/rgb_matrix_effect/rainbow_sin_wave_reverse.h"

#include "zqlib/rgb_matrix_effect/candy_tap.h"

#include "zqlib/rgb_matrix_effect/cycle_reactive_multiwide.h"
#include "zqlib/rgb_matrix_effect/cycle_reactive_multicross.h"
#include "zqlib/rgb_matrix_effect/cycle_reactive_multinexus.h"
#include "zqlib/rgb_matrix_effect/cycle_multisplash.h"


// #include "zqlib/rgb_matrix_effect/reactive_multiwide_rgb.h"
// #include "zqlib/rgb_matrix_effect/reactive_multicross_rgb.h"
// #include "zqlib/rgb_matrix_effect/reactive_multinexus_rgb.h"


