RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
VIA_ENABLE = yes
LTO_ENABLE = yes
RGB_MATRIX_CONTROL_ENABLE = yes
UNDERGLOW_RGB_MATRIX_ENABLE = yes
OPENRGB_ENABLE = yes
VIA_CUSTOM_KEYCODE_ENABLE = yes




