ENCODER_ENABLE = yes
VIA_ENABLE = yes
RGB_MATRIX_CUSTOM_KB = yes
WPM_ENABLE = yes
VELOCIKEY_ENABLE = yes
TAP_DANCE_ENABLE = no
UNICODEMAP_ENABLE = yes
OLED_ENABLE = yes
RGB_MATRIX_CONTROL_ENABLE = yes
UNDERGLOW_RGB_MATRIX_ENABLE = yes
ENCODER_TRIGGER_ENABLE = yes
ALT_TAB_MARCO_ENABLE = yes
OPENRGB_ENABLE = yes


